addpath('./source/kinematics', './source/control', './source/dynamics', ...
    './source/set_parameters/','./source/solve_eqns/', './source/visualize', ...
    './source/analysis', './source/test_results')
test_the_results